export enum ModalTypeEnum {
  SIGN_IN_MODAL = "SIGN_IN_MODAL",
  SIGN_UP_MODAL = "SIGN_UP_MODAL",
  ADD_ORDER_MODAL = "ADD_ORDER_MODAL",
  ADD_PRODUCT_MODAL = "ADD_PRODUCT_MODAL",
  EDIT_PRODUCT_MODAL = "EDIT_PRODUCT_MODAL",
}
